[package]
name = "chip"
version = "0.1.0"
authors = ["Darryl Walker <darryljwalker@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
log = "0.4.14"
env_logger = "0.8.3"
chrono = "0.4.19"
